/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "maben",
    "x": -256.43947896796266,
    "z": -34.26191002008607
  },
  {
    "name": "Wonkenstein",
    "x": -265.82165879642736,
    "z": -54.14221444845552
  },
  {
    "name": "maben",
    "x": -411.0626490898936,
    "z": -201.214844515225
  },
  {
    "name": "Boss_Cross_Man",
    "x": -426.8009288241825,
    "z": -281.4849061719296
  }
]
