/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "maben",
    "x": -256.43947896796266,
    "z": -34.26191002008607
  },
  {
    "name": "maben",
    "x": -385.5565916788397,
    "z": -223.30673685830055
  },
  {
    "name": "Boss_Cross_Man",
    "x": -273.81883732531827,
    "z": -66.43258424706298
  },
  {
    "name": "Wonkenstein",
    "x": -564.4404812266723,
    "z": -652.466110981609
  }
]
