/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "maben",
    "x": -256.43947896796266,
    "z": -34.26191002008607
  },
  {
    "name": "Boss_Cross_Man",
    "x": -426.8009288241825,
    "z": -281.4849061719296
  },
  {
    "name": "maben",
    "x": -280.0292389553706,
    "z": -66.57094328731222
  },
  {
    "name": "Wonkenstein",
    "x": -221.27106484256498,
    "z": -1497.4580642924889
  }
]
