/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "maben",
    "x": 3.561542459307862,
    "z": 10.47928453446892
  },
  {
    "name": "maben",
    "x": 943.6999999880791,
    "z": 985.9301719860204
  },
  {
    "name": "Boss_Cross_Man",
    "x": -121.73851334812746,
    "z": 113.56951082673159
  },
  {
    "name": "Wonkenstein",
    "x": 794.3439090462789,
    "z": 1293.1710589640743
  }
]
